caixa/urls.py
from django.urls import path
from .models import Pessoa
from . import views as v

app_name = 'caixa'

urlpatterns = [
    path('', v.cx_list, name = 'cx_list'),
    path('caixa/list', v.cx_list, name = 'cx_list'),
    path('caixa/filter', v.cx_filter, name = 'cx_filter'),
    path('caixa/lote', v.cx_lote, name = 'cx_lote'),
    path('caixa/new', v.cx_new, name = 'cx_new'),
    path('caixa/detail/<int:pk>', v.cx_detail, name = 'cx_detail'),
    path('parc-autocomplete/', v.ParcAutocomplete.as_view(model=Pessoa, create_field='nome'), name='parc-autocomplete'),
    path('conta-autocomplete/', v.ContaAutocomplete.as_view(), name='conta-autocomplete'),



]

core/urls.py
from django.urls import path
from . import views as v

app_name = 'core'

urlpatterns = [
    path('', v.index, name='index'),
]

meucaixa/urls.py
from django.contrib import admin
from django.urls import path, include

admin.site.site_header = 'Meu Caixa .feito'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('core.urls')),
    path('', include('caixa.urls')),
   
]

core/models.py
from django.db import models
from django.contrib.auth.models import User


class TimeStampedModel(models.Model):
    created = models.DateTimeField(
        'criado em',
        blank=True, null=True,
        auto_now_add=True,
        auto_now=False
    )
    modified = models.DateTimeField(
        'modificado em',
        blank=True, null=True,
        auto_now_add=False,
        auto_now=True
    )

    class Meta:
        abstract = True


class LogModel(models.Model):
    criado = models.DateTimeField(auto_now_add=True)
    criadoPor = models.ForeignKey(User, on_delete=models.PROTECT, blank=True)
    modificado = models.DateTimeField(auto_now=True)
    modificadoPor = models.ForeignKey(User, on_delete=models.PROTECT, blank=True)

    class Meta:
        abstract = True

core/views.py
from django.shortcuts import render
from django.http.response import HttpResponse

def index(request):
    return render (request, 'index.html')

core/templates/includes/nav.html
  
<!-- https://github.com/JTruax/bootstrap-starter-template/blob/master/template/start.html -->

<nav class="navbar navbar-expand-md navbar-dark bg-dark sticky-top">
    <a class="navbar-brand" href="#">
        <img alt="Feito!" src="/static/media/feito_ico.png"
        width="40" height="40">
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'core:index' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Cadastros</a>
                <div class="dropdown-menu" aria-labelledby="dropdown01">
                    <a class="dropdown-item" href="/pessoa/">Lista Pessoas (s)</a>
                    <a class="dropdown-item" href="/pessoa/s">Pesquisa Pessoas (s)</a>
                    <a class="dropdown-item" href="/pessoa/n">Nova Pessoa</a>             
                </div>
            </li>

            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Caixa</a>
                <div class="dropdown-menu" aria-labelledby="dropdown02">
                    <a class="dropdown-item" href="/caixa/list">Extrato</a> 
                    <a class="dropdown-item" href="/caixa/new">Novo Lançamento</a>
                </div>
            </li>

        </ul>

        {% if user.is_authenticated %}
          <ul class="navbar-nav px-3">
            <li class="nav-item text-nowrap">
              <a class="nav-link" href="/accounts/logout">Sair</a>
            </li>
          </ul>
        {% endif %}
    </div>
</nav>