caixa/urls.py
from django.urls import path
from .models import Pessoa
from . import views as v

app_name = 'caixa'

urlpatterns = [
    path('', v.cx_list, name = 'cx_list'),
    path('caixa/list', v.cx_list, name = 'cx_list'),
    path('caixa/filter', v.cx_filter, name = 'cx_filter'),
    path('caixa/lote', v.cx_lote, name = 'cx_lote'),
    path('caixa/new', v.cx_new, name = 'cx_new'),
    path('caixa/detail/<int:pk>', v.cx_detail, name = 'cx_detail'),
    path('parc-autocomplete/', v.ParcAutocomplete.as_view(model=Pessoa, create_field='nome'), name='parc-autocomplete'),
    path('conta-autocomplete/', v.ContaAutocomplete.as_view(), name='conta-autocomplete'),



]

core/urls.py
from django.urls import path
from . import views as v

app_name = 'core'

urlpatterns = [
    path('', v.index, name='index'),
]

meucaixa/urls.py
from django.contrib import admin
from django.urls import path, include

admin.site.site_header = 'Meu Caixa .feito'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('core.urls')),
    path('', include('caixa.urls')),
   
]

caixa/models.py
from django.db import models
from django.db.models.deletion import CASCADE, PROTECT

TIPO_CONTA = (
    ('RE', 'RECEITA'),
    ('DE', 'DESPESA'),
    ('IN', 'INVESTIMENTO')
)

BANCO_CHOICES = (
    ('BP', 'BANRISUL PASQUALOTO'),
    ('BRP', 'BANRISUL RP'),
    ('SP', 'SICREDI')
)

class Conta(models.Model):
    cod = models.CharField(max_length=6)
    conta = models.CharField(max_length=80)
    tipo = models.CharField(max_length=2, choices=TIPO_CONTA, null=True, blank=True)

    def __str__(self):
        return self.conta

class Pessoa(models.Model):
    nome = models.CharField(max_length=40)
    
    def __str__(self):
        return self.nome


class CC(models.Model):
    data = models.DateField()
    desc = models.CharField(max_length=80)
    banco = models.CharField(max_length=4, choices=BANCO_CHOICES, null=True, blank=True)
    conta = models.ForeignKey(Conta, on_delete=PROTECT, null=True, blank=True)
    pessoa = models.ForeignKey(Pessoa, on_delete=PROTECT, null=True, blank=True)
    credito = models.DecimalField(max_digits=13, decimal_places=2, default=0)
    debito = models.DecimalField(max_digits=13, decimal_places=2, default=0)

    def __str__(self):
        return self.desc

caixa/forms.py
from django import forms
from .models import *
from django.forms import ModelForm, fields, Form
from dal import autocomplete

LOTE_OPCOES = (
    ('0','Ações em lote'),
    ('1','Baixar com data de hoje'),
    ('2','Baixar com data do vencimento'),
    ('3', 'Somar')
)


class CX_detail_form(ModelForm):
    
    #entrada = forms.CharField(max_length=60, label='Nota de entrada', required=False, disabled=False, widget=forms.TextInput(attrs={'size': '60'}))

    class Meta:
        model = CC
        fields = '__all__'
        widgets = {
            'pessoa': autocomplete.ModelSelect2(
                url='caixa:parc-autocomplete',
                attrs={'data-minimum-input-length': 3,
                        'dropdownAutoWidth': True,
                },
                ),          

            'conta': autocomplete.ModelSelect2(
                url='caixa:conta-autocomplete',
                attrs={'data-minimum-input-length': 3,
                        'dropdownAutoWidth': True,
                },
                ),          

        }

class CX_acoes_lote_form(Form):
    opcoes = forms.ChoiceField(choices = LOTE_OPCOES, label="")

caixa/views.py
from django.shortcuts import redirect, render, get_object_or_404, HttpResponse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .filters import CX_Filter
from .forms import *
from .models import CC, Conta, Pessoa
from dal import autocomplete
import json
import pandas as pd
import numpy as np
import openpyxl
from datetime import datetime
from decimal import *
from .models import CC, Conta


def cx_list(request):
    pass


def import_conta():
    df = pd.read_csv (r'c:\dados2.csv', delimiter=';')

    ct_list = df['CONTA'].unique()
    for ct in ct_list:
        print(ct)
        conta = Conta()
        conta.conta = ct
        conta.save()

    #print(ct)
    #for index, row in df.iterrows():
    # print(row["DESC"])


def import_dados():
    df = pd.read_csv (r'c:\dados2.csv', delimiter=';')

    cc = CC.objects.all().delete()
    for index, row in df.iterrows():
        conta = Conta.objects.filter(conta=row['CONTA'])
        data  = datetime.strptime(row['DATA'], '%d/%m/%Y')
        credito = Decimal(row['CREDITO'].replace(',', '.'))
        debito = Decimal(row['DEBITO'].replace(',', '.'))
        cc = CC()
        cc.data = data
        cc.desc = row['DESC']
        cc.banco = row['BANCO']
        cc.conta = conta[0]
        cc.credito = credito
        cc.debito = debito
        cc.save()


def to_pandas():
    df = pd.DataFrame(list(CC.objects.all().values('conta__conta', 'banco', 'credito', 'debito' )))
    print(df)

    table = pd.pivot_table(df, index=['conta__conta'], aggfunc={'credito': np.sum, 'debito': np.sum})
    print(table)
    table.to_excel("c:\django\output4.xlsx") 
    #table.to_csv('c:\django\output.csv', sep=';') 



#import_conta()
#import_dados()
#to_pandas()









class ParcAutocomplete(autocomplete.Select2QuerySetView):
    def get_queryset(self):
        print('nome-autocomplete')
        if not self.request.user.is_authenticated:
            return Pessoa.objects.none()
        qs = Pessoa.objects.only('nome')
        if self.q:
            qs = qs.filter(nome__icontains=self.q)
        return qs


class ContaAutocomplete(autocomplete.Select2QuerySetView):
    def get_queryset(self):
        print('conta-autocomplete')
        if not self.request.user.is_authenticated:
            return Pessoa.objects.none()
        qs = Conta.objects.only('conta')
        if self.q:
            qs = qs.filter(conta__icontains=self.q)
        return qs


def cx_list(request):
    lista = CX_Filter(request.GET, queryset=CC.objects.all().order_by('-data'))
    paginator = Paginator(lista.qs, 20) # Show 25 contacts per page.
    page_number = request.GET.get('page', 1)

    lote = CX_acoes_lote_form()

    try:
        page_obj = paginator.get_page(page_number)
    except PageNotAnInteger:
        page_obj = paginator.page(1)
    except EmptyPage:
        page_obj = paginator.page(paginator.num_pages)

    return render(request, 'caixa/cx_list.html', {'page_obj': page_obj, 'lista': lista, 'lote': lote})



def cx_filter(request):

    lista = CC.objects.all().order_by('-data')
    paginator = Paginator(lista, 20) # Show 25 contacts per page.
    
    page_number = request.GET.get('page', 1)

    try:
        page_obj = paginator.get_page(page_number)
    except PageNotAnInteger:
        page_obj = paginator.page(1)
    except EmptyPage:
        page_obj = paginator.page(paginator.num_pages)

    return render(request, 'caixa/cx_list.html', {'page_obj': page_obj })

def cx_lote(request):

    chkeds = request.POST.get('chkeds')
    opt = request.POST.get('opt')
    print("Estes são os selecionados", chkeds, " com esta opcao: ", opt )

    dict = {'ret': "oi"}
    return HttpResponse(json.dumps(dict), content_type='application/json')



def cx_detail(request, pk):
    cx = get_object_or_404(CC, pk=pk)
    if request.method == 'POST':
        #print(request.POST)
        act = request.POST['act']

        if act == 'delete':
            cx.delete()
            form = CX_detail_form()
            return redirect('caixa:cx_list')
        elif act == 'save':
            print('act=save')
            form = CX_detail_form(request.POST, instance = cx)
            if form.is_valid():
                print('form is valid')
                #form = ProdDetailForm(form.cleaned_data)
                form.save()
            return redirect('/caixa/new')
    else:
        form = CX_detail_form(instance=cx)
        return render(request, 'caixa/cx_detail.html', {'form': form, 'inst_id':pk})


def cx_new(request):
    if request.method == 'POST':
        form = CX_detail_form(request.POST)
        if form.is_valid():
            inst = form.save(commit=False)
            inst.save()
            return redirect('caixa:cx_detail', pk=inst.pk)
        else:
            return render(request, 'caixa/cx_detail.html', {'form': form})
    else:
        form = CX_detail_form()
        return render(request, 'caixa/cx_detail.html', {'form': form})

caixa/templates/caixa/cx_detail.html
{% extends "base.html" %}
{% load crispy_forms_tags %}


{% block content %}
<div class="jumbotron">
    <form method="post" id="MyForm">
        {% csrf_token %}
        <div class="form-row">
            <div class="form-group col-md-6 mb-0">
                <h1>Contas a Pagar</h1>
            </div>
            <div class="form-group col-md-6 mb-0">
                <button type="submit" name="act" value="save"id="salvar" class="btn btn-primary">Salvar</button>
                <a href="/caixa/new"> <button type="button" class="btn btn-primary">Novo</button></a>
                <a href="/caixa/list"> <button type="button" class="btn btn-primary">Pesquisar</button></a>
                <button type="submit" name="act" value="delete" class="btn btn-primary">Deletar</button>
            </div>
        </div>
        <div class="form-row">
            <div class="form-group col-md-2 mb-0">
                {{ form.banco|as_crispy_field }}
            </div>

            <div class="form-group col-md-4 mb-0">
                {{ form.conta|as_crispy_field }}
            </div>
            <div class="form-group col-md-4 mb-0">
                {{ form.pessoa|as_crispy_field }}
            </div>
            <div class="form-group col-md-2 mb-0">
                {{ form.data|as_crispy_field }}
            </div>
        </div>
        <div class="form-row">
            <div class="form-group col-md-6 mb-0">
                {{ form.desc|as_crispy_field }}
            </div>
            <div class="form-group col-md-3 mb-0">
                {{ form.credito|as_crispy_field }}
            </div>
            <div class="form-group col-md-3 mb-0">
                {{ form.debito|as_crispy_field }}
            </div>
        </div>
    </form>
</div>
{% endblock %}

{% block extrascripts %}
{{ form.media }}
<script>
     
    const dt = document.getElementById('id_data');
    dt.addEventListener("change", dt_function);

    function dt_function(e) {
        const today = new Date();
        let dt = document.getElementById("id_data").value;
        let new_date = addDays(today, dt);
        document.getElementById("id_data").value = new_date
        };

    function addDays(date, days) {
        const isNum = checkValue(days);
        console.log(isNum);
        if (isNum){
            const nDays = parseInt(days, 10);
            var newDate = new Date(date);
            newDate.setDate(newDate.getDate() + nDays);
            const dataFormatada = ((newDate.getDate() ) + "/" + ((newDate.getMonth() + 1)) + "/" + newDate.getFullYear());                 
            return dataFormatada;        
        } else {
            return days
        }
        };

    function checkValue(val){
        const num = parseInt(val, 10);
        console.log(num);
        return !isNaN(val)
        };
    
    function retDate(dateString){
        var parts =dateString.split('/');
        // Please pay attention to the month (parts[1]); JavaScript counts months from 0:
        // January - 0, February - 1, etc.
        var mydate = new Date(parts[2], parts[1] - 1, parts[0]); 
        console.log(mydate.toDateString());
        return mydate
    }

</script>

{% endblock extrascripts %}

caixa/templates/caixa/cx_list.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}

<div class="container-fluid">

  <div class="form-row">
    <div class="form-group col-md-4 mb-0">
      <h4><strong>Contas a Pagar</strong></h4>
    </div>
    <div class="form-group col-md-4 mb-0">
      <form method="get" id="acao_lote"></form>
      {{ lote.opcoes|as_crispy_field }}
    </div>
    <div class="form-group col-md-4 mb-0">
      <button type="button" class="btn btn-primary" onclick="lote(this);">Executar</button>
      <button id="filter" class="filter-pedido btn btn-primary" type="button" name="button" data-form-url="{% url 'caixa:cx_filter' %}">
        <span class="fa fa-filter mr-2"></span>Filtrar
      </button>
    </div>
  </form>
</div>

  <p> </p>   
  {% include "caixa/cx_list_table.html" %}     


</div>

<div class="modal fade" id="filtro" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered modal-lg " role="document">
    <div class="modal-content">
      
      <div class="modal-header">
        <h5 class="modal-title" id="send_mail">Filtro de lancamentos</h5>       
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
      </div>

      <div class="modal-body">
        <div class="container" id="filtro">
          <form method="get" id="filtro-form">
            {{ lista.form|crispy }}
            <button type="submit" class="btn btn-primary" >Filtrar</button>
          </form>
        </div>
      </div>

    </div>
  </div>
</div>

{% endblock content %}

{% block extrascripts %}
<script type="text/javascript">

  $(".detail").click(function(){
    var url = $(this).attr('data-form-url');
    location.href = url  
  });

  $(".read").click(function(){
    var url = $(this).attr('data-form-url');
    $(this).modalForm({formURL: $(this).data("form-url")}); 
  });

  $("#filter").click(function () {
    $("#filtro").modal('toggle')
  });


  function toggle(source) {
    var checkboxes = document.querySelectorAll('input[type="checkbox"]');
    for (var i = 0; i < checkboxes.length; i++) {
        if (checkboxes[i] != source)
            checkboxes[i].checked = source.checked;
    }
  }

  function lote(source) {
    let checkboxes = document.querySelectorAll('input[name="chk"]:checked');
    let lote_opt = document.getElementById("id_opcoes").value
    let values = [];
    checkboxes.forEach((checkbox) => {
        values.push(checkbox.value);
    });
    console.log(values);
    console.log(lote_opt);
    send_lote(values, lote_opt)
  } 

  function send_lote(chkeds, opt) {

    let data = new FormData();
    data.append('chkeds', chkeds);;
    data.append('opt', opt);
    // add form input from hidden input elsewhere on the page
    data.append('csrfmiddlewaretoken', '{{ csrf_token }}')

    console.log(JSON.stringify(data))

    fetch("{% url 'caixa:cx_lote' %}", {
        method: 'POST',
        body: data,
        credentials: 'same-origin',
        headers: {"X-CSRFToken": '{{ csrf_token }}'}
    }).then((response) => {
        console.log(response)
    }).then((res) => {
        if (res.status === 201) {
            console.log("Post successfully created!")
        }
    }).catch((error) => {
        console.log(error)
    })
  }

</script>
{% endblock extrascripts %}

caixa/templates/caixa/cx_list_table.html
<table id="entrega-list-table" class="table table-hover">
  <thead class="thead-light ">
  <tr>
    <th class="text-center chkAll" scope="col"><input type="checkbox" onclick="toggle(this);"></th>
    <th class="text-center" scope="col">Banco</th>
    <th class="text-center" scope="col">Data</th>
    <th class="text-center" scope="col">Pessoa</th>
    <th class="text-center" scope="col">Conta</th>
    <th class="text-center" scope="col">Descrição</th>
    <th class="text-center" scope="col">Crédito</th>
    <th class="text-center" scope="col">Débito</th>
    <th class="text-center" scope="col">Detalhe</th>
  </tr>
  </thead>
  <tbody>
  {% for it in page_obj.object_list %}
    <tr>
      <!-- <th class="text-center" scope="row">{{ forloop.counter }}</th> -->
      <td class="text-center chk" ><input type="checkbox" name="chk" value="{{ it.pk }}"></td>
      <td class="text-center">{{ it.banco }}</td>
      <td class="text-center">{{ it.data|date:"SHORT_DATE_FORMAT" }}</td>
      <td class="text-center">{{ it.pessoa }}</td>
      <td class="text-center">{{ it.conta }}</td>
      <td class="text-center">{{ it.desc }}</td>
      <td class="text-center">{{ it.credito }}</td>
      <td class="text-center">{{ it.debito }}</td>
      
      <td class="text-center">
        <!-- open pedido full -->
        <button type="button" id='detail' class="detail btn btn-sm btn-primary" data-form-url="{% url 'caixa:cx_detail' it.pk %}" >
          <span class="fa fa-pencil"></span>
        </button>
      </td>
    </tr>
  {% endfor %}

  </tbody>
</table>

<div>
  <nav aria-label="Page navigation example">
    <ul class="pagination">
      {% if page_obj.has_other_pages %}
        {% if page_obj.has_previous %}
          {% if 'banco' in request.get_full_path %}
            <li class="page-item"><a class="page-link" href="{{ request.get_full_path }}&page={{ page_obj.previous_page_number }}">Anterior</a></li>
          {% else %}
            <li class="page-item"><a class="page-link" href="{% url 'caixa:cx_list' %}?page={{ page_obj.previous_page_number }}">Anterior</a></li>
          {% endif %}
        {% else %}
          <li class="disabled page-link"><span>Anterior</span></li>
        {% endif %}
        
        
        {% for i in page_obj.paginator.get_elided_page_range %}
          {% if page_obj.number == i %}
            <li class="page-item active">
              <a class="page-link" href="#">{{ i }} <span class="sr-only">(current)</span></a>
            </li>
          {% else %}
            {% if 'banco' in request.get_full_path %}
              <li class="page-item"><a class="page-link" href="{{ request.get_full_path }}&page={{ i }}">{{ i }}</a></li>
            {% else %}
              <li class="page-item"><a class="page-link" href="{% url 'caixa:cx_list' %}?page={{ i }}">{{ i }}</a></li>
            {% endif %}
          {% endif %}
        {% endfor %}


        {% if page_obj.has_next %}
          {% if 'banco' in request.get_full_path %}
            <li class="page-item"><a class="page-link" href="{{ request.get_full_path }}&page={{ page_obj.next_page_number }}">Próxima</a></li>
          {% else %}
            <li class="page-item"><a class="page-link" href="{% url 'caixa:cx_list' %}?page={{ page_obj.next_page_number }}">Próxima</a></li>
          {% endif %}

        {% else %}
          <li class="disabled page-link "><span>Próxima</span></li>
        {% endif %}

      {% endif %}
    </ul>
  </nav>
</div>