caixa/urls.py
from django.urls import path
from .models import Pessoa
from . import views as v

app_name = 'caixa'

urlpatterns = [
    path('', v.cx_list, name = 'cx_list'),
    path('caixa/list', v.cx_list, name = 'cx_list'),
    path('caixa/filter', v.cx_filter, name = 'cx_filter'),
    path('caixa/lote', v.cx_lote, name = 'cx_lote'),
    path('caixa/new', v.cx_new, name = 'cx_new'),
    path('caixa/detail/<int:pk>', v.cx_detail, name = 'cx_detail'),
    path('parc-autocomplete/', v.ParcAutocomplete.as_view(model=Pessoa, create_field='nome'), name='parc-autocomplete'),
    path('conta-autocomplete/', v.ContaAutocomplete.as_view(), name='conta-autocomplete'),



]

core/urls.py
from django.urls import path
from . import views as v

app_name = 'core'

urlpatterns = [
    path('', v.index, name='index'),
]

financeiro/urls.py
from django.urls import path

from . import views as v

app_name = 'financeiro'

urlpatterns = [
    path('cp/list', v.cp_list, name = 'cp_list'),
    path('cp/filter', v.cp_filter, name = 'cp_filter'),
    path('cp/lote', v.cp_lote, name = 'cp_lote'),
    path('cp/new', v.cp_new, name = 'cp_new'),
    path('cp/detail/<int:pk>', v.cp_detail, name = 'cp_detail'),
    path('parc-autocomplete/', v.ParcAutocomplete.as_view(), name='parc-autocomplete'),
    path('entrada-autocomplete/', v.EntradaAutocomplete.as_view(), name='entrada-autocomplete'),
    
    #CR
    path('cr/list', v.cr_list, name = 'cr_list'),
    path('cr/filter', v.cr_filter, name = 'cr_filter'),
    path('cr/lote', v.cr_lote, name = 'cr_lote'),
    path('cr/new', v.cr_new, name = 'cr_new'),
    path('cr/detail/<int:pk>', v.cr_detail, name = 'cr_detail'),
    path('parc-autocomplete/', v.ParcAutocomplete.as_view(), name='parc-autocomplete'),
    path('entrega-autocomplete/', v.EntregaAutocomplete.as_view(), name='entrega-autocomplete'),


]

meucaixa/urls.py
from django.contrib import admin
from django.urls import path, include

admin.site.site_header = 'Meu Caixa .feito'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('core.urls')),
    path('', include('caixa.urls')),
   
]

financeiro/forms.py
from django import forms
#from django.forms.widgets import HiddenInput
from .models import *
#from django.forms.models import inlineformset_factory
#from crispy_forms.helper import FormHelper
#from crispy_forms.layout import Button, Hidden, Layout, Field, Fieldset, Div, HTML, ButtonHolder, Submit
from django.forms import ModelForm, fields, Form
#from crispy_forms.helper import FormHelper
#from crispy_forms.layout import Layout, Submit, Row, Column
#from django.forms.formsets import BaseFormSet
#from decimal import Decimal
from dal import autocomplete

CP_OPCOES = (
    ('0','Ações em lote'),
    ('1','Baixar com data de hoje'),
    ('2','Baixar com data do vencimento'),
    ('3', 'Somar')
)


class CP_detail_form(ModelForm):
    
    #entrada = forms.CharField(max_length=60, label='Nota de entrada', required=False, disabled=False, widget=forms.TextInput(attrs={'size': '60'}))

    class Meta:
        model = Conta_pagar
        fields = '__all__'
        widgets = {
            'parceiro': autocomplete.ModelSelect2(
                url='cadastro:nome-autocomplete',
                attrs={'data-minimum-input-length': 3,
                        'dropdownAutoWidth': True,
                },
                ),
            'entrada': autocomplete.ModelSelect2(
                url='financeiro:entrada-autocomplete',
                attrs={'data-minimum-input-length': 3,
                        'dropdownAutoWidth': True,
                },
                ),
            
        }

class CP_acoes_lote_form(Form):
    opcoes = forms.ChoiceField(choices = CP_OPCOES, label="")


CR_OPCOES = (
    ('0','Ações em lote'),
    ('1','Baixar com data de hoje'),
    ('2','Baixar com data do vencimento'),
    ('3','Emitir Boleto Banrisul'),
    ('4','Enviar XML por e-mail'),
    ('3', 'Somar')
)

class CR_acoes_lote_form(Form):
    opcoes = forms.ChoiceField(choices = CR_OPCOES, label="")

class CR_detail_form(ModelForm):
    
    #entrada = forms.CharField(max_length=60, label='Nota de entrada', required=False, disabled=False, widget=forms.TextInput(attrs={'size': '60'}))

    class Meta:
        model = Conta_receber
        fields = '__all__'
        widgets = {
            'parceiro': autocomplete.ModelSelect2(
                url='cadastro:nome-autocomplete',
                attrs={'data-minimum-input-length': 3,
                        'dropdownAutoWidth': True,
                },
                ),
            'entrega': autocomplete.ModelSelect2(
                url='financeiro:entrega-autocomplete',
                attrs={'data-minimum-input-length': 3,
                        'dropdownAutoWidth': True,
                },
                ),
            
        }

financeiro/views.py
from django.shortcuts import redirect, render, get_object_or_404, HttpResponse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .filters import CP_Filter, CR_Filter
from .forms import *
from .models import Conta_pagar, Conta_receber
from cadastro.models import Parceiro
from entradas.models import NF_entrada
from dal import autocomplete
import json



class ParcAutocomplete(autocomplete.Select2QuerySetView):
    def get_queryset(self):
        print('nome-autocomplete')
        if not self.request.user.is_authenticated:
            return Parceiro.objects.none()
        qs = Parceiro.objects.only('nome')
        if self.q:
            qs = qs.filter(nome__icontains=self.q)
        return qs
        
class EntradaAutocomplete(autocomplete.Select2QuerySetView):
    def get_queryset(self):
        print('nome-autocomplete')
        if not self.request.user.is_authenticated:
            return NF_entrada.objects.none()
        qs = NF_entrada.objects.only('num', 'parceiro')
        if self.q:
            qs = qs.filter(parceiro__nome__icontains=self.q)
        return qs

class EntregaAutocomplete(autocomplete.Select2QuerySetView):
    def get_queryset(self):
        print('entrega-autocomplete')
        if not self.request.user.is_authenticated:
            return Entrega.objects.none()
        qs = Entrega.objects.only('num_nf', 'parceiro')
        if self.q:
            qs = qs.filter(parceiro__nome__icontains=self.q)
        return qs

def cp_list(request):
    lista = CP_Filter(request.GET, queryset=Conta_pagar.objects.all().order_by('-data_vencimento'))
    paginator = Paginator(lista.qs, 20) # Show 25 contacts per page.
    page_number = request.GET.get('page', 1)

    lote = CP_acoes_lote_form()

    try:
        page_obj = paginator.get_page(page_number)
    except PageNotAnInteger:
        page_obj = paginator.page(1)
    except EmptyPage:
        page_obj = paginator.page(paginator.num_pages)

    return render(request, 'financeiro/cp_list.html', {'page_obj': page_obj, 'lista': lista, 'lote': lote})



def cp_filter(request):

    lista = Conta_pagar.objects.all().order_by('-data_emissao')
    paginator = Paginator(lista, 20) # Show 25 contacts per page.
    
    page_number = request.GET.get('page', 1)

    try:
        page_obj = paginator.get_page(page_number)
    except PageNotAnInteger:
        page_obj = paginator.page(1)
    except EmptyPage:
        page_obj = paginator.page(paginator.num_pages)

    return render(request, 'financeiro/cp_list.html', {'page_obj': page_obj })

def cp_lote(request):

    chkeds = request.POST.get('chkeds')
    opt = request.POST.get('opt')
    print("Estes são os selecionados", chkeds, " com esta opcao: ", opt )

    dict = {'ret': "oi"}
    return HttpResponse(json.dumps(dict), content_type='application/json')



def cp_detail(request, pk):
    cp = get_object_or_404(Conta_pagar, pk=pk)
    if request.method == 'POST':
        #print(request.POST)
        act = request.POST['act']

        if act == 'delete':
            cp.delete()
            form = CP_detail_form()
            return redirect('financeiro:cp_list')
        elif act == 'save':
            print('act=save')
            #pr = get_object_or_404(Prod, pk=prod_id)
            form = CP_detail_form(request.POST, instance = cp)
            if form.is_valid():
                print('form is valid')
                #form = ProdDetailForm(form.cleaned_data)
                form.save()
            return render(request, 'financeiro/cp_detail.html', {'form': form})
        elif act =='quitar':
            print('act=quitar')
            #pr = get_object_or_404(Prod, pk=prod_id)
            form = CP_detail_form(request.POST, instance = cp)
            if form.is_valid():
                form.data_pagamento = cp.data_vencimento
                form.valor_pago = cp.valor_parcela
                #print('form is valid')
                #form = ProdDetailForm(form.cleaned_data)
                form.save()
            return render(request, 'financeiro/cp_detail.html', {'form': form})
    else:
        form = CP_detail_form(instance=cp)
        return render(request, 'financeiro/cp_detail.html', {'form': form, 'cp_id':pk})


def cp_new(request):
    if request.method == 'POST':
        form = CP_detail_form(request.POST)
        if form.is_valid():
            cp = form.save(commit=False)
            cp.save()
            return redirect('financeiro:cp_detail', pk=cp.pk)
        else:
            return render(request, 'prod/prod_detail.html', {'form': form})
    else:
        form = CP_detail_form()
        return render(request, 'financeiro/cp_detail.html', {'form': form})


def cr_list(request):
    pass




####Contas a Receber

def cr_list(request):
    lista = CR_Filter(request.GET, queryset=Conta_receber.objects.all().order_by('-data_vencimento'))
    paginator = Paginator(lista.qs, 20) # Show 25 contacts per page.
    page_number = request.GET.get('page', 1)

    lote = CR_acoes_lote_form()

    try:
        page_obj = paginator.get_page(page_number)
    except PageNotAnInteger:
        page_obj = paginator.page(1)
    except EmptyPage:
        page_obj = paginator.page(paginator.num_pages)

    return render(request, 'financeiro/cr_list.html', {'page_obj': page_obj, 'lista': lista, 'lote': lote})



def cr_filter(request):

    lista = Conta_receber.objects.all().order_by('-data_emissao')
    paginator = Paginator(lista, 20) # Show 25 contacts per page.
    
    page_number = request.GET.get('page', 1)

    try:
        page_obj = paginator.get_page(page_number)
    except PageNotAnInteger:
        page_obj = paginator.page(1)
    except EmptyPage:
        page_obj = paginator.page(paginator.num_pages)

    return render(request, 'financeiro/cr_list.html', {'page_obj': page_obj })

def cr_lote(request):

    chkeds = request.POST.get('chkeds')
    opt = request.POST.get('opt')
    print("Estes são os selecionados", chkeds, " com esta opcao: ", opt )
    dict = {'ret': "oi"}
    return HttpResponse(json.dumps(dict), content_type='application/json')



def cr_detail(request, pk):
    cr = get_object_or_404(Conta_receber, pk=pk)
    if request.method == 'POST':
        #print(request.POST)
        act = request.POST['act']

        if act == 'delete':
            cr.delete()
            form = CR_detail_form()
            return redirect('financeiro:cr_list')
        elif act == 'save':
            print('act=save')
            #pr = get_object_or_404(Prod, pk=prod_id)
            form = CR_detail_form(request.POST, instance = cr)
            if form.is_valid():
                print('form is valid')
                #form = ProdDetailForm(form.cleaned_data)
                form.save()
            return render(request, 'financeiro/cr_detail.html', {'form': form})
        elif act =='quitar':
            print('act=quitar')
            #pr = get_object_or_404(Prod, pk=prod_id)
            form = CR_detail_form(request.POST, instance = cr)
            if form.is_valid():
                form.data_pagamento = cr.data_vencimento
                form.valor_pago = cr.valor_parcela
                #print('form is valid')
                #form = ProdDetailForm(form.cleaned_data)
                form.save()
            return render(request, 'financeiro/cr_detail.html', {'form': form})
    else:
        form = CR_detail_form(instance=cr)
        return render(request, 'financeiro/cr_detail.html', {'form': form, 'cr_id':pk})


def cr_new(request):
    if request.method == 'POST':
        form = CR_detail_form(request.POST)
        if form.is_valid():
            cr = form.save(commit=False)
            cr.save()
            return redirect('financeiro:cr_detail', pk=cr.pk)
        else:
            return render(request, 'prod/prod_detail.html', {'form': form})
    else:
        form = CR_detail_form()
        return render(request, 'financeiro/cr_detail.html', {'form': form})

financeiro/templates/financeiro/cp_detail.html
{% extends "base.html" %}
{% load crispy_forms_tags %}


{% block content %}
<div class="jumbotron">
    <form method="post" id="MyForm">
        {% csrf_token %}
        <div class="form-row">
            <div class="form-group col-md-6 mb-0">
                <h1>Contas a Pagar</h1>
            </div>
            <div class="form-group col-md-6 mb-0">
                <button type="submit" name="act" value="save"id="salvar" class="btn btn-primary">Salvar</button>
                <a href="/fin/cp/new"> <button type="button" class="btn btn-primary">Novo</button></a>
                <a href="/fin/cp/list"> <button type="button" class="btn btn-primary">Pesquisar</button></a>
                <button type="submit" name="act" value="delete" class="btn btn-primary">Deletar</button>
                <button type="button" class="btn btn-primary" onclick="quitar(this);">Quitar</button>
            </div>
        </div>
        <div class="form-row">
            <div class="form-group col-md-6 mb-0">
                {{ form.parceiro|as_crispy_field }}
            </div>

            <div class="form-group col-md-2 mb-0">
                {{ form.num_nf|as_crispy_field }}
            </div>
            <div class="form-group col-md-2 mb-0">
                {{ form.num_parcela|as_crispy_field }}
            </div>
            <div class="form-group col-md-2 mb-0">
                {{ form.data_emissao|as_crispy_field }}
            </div>
        </div>
        <div class="form-row">
            <div class="form-group col-md-3 mb-0">
                {{ form.data_vencimento|as_crispy_field }}
            </div>
            <div class="form-group col-md-3 mb-0">
                {{ form.data_pagamento|as_crispy_field }}
            </div>
            <div class="form-group col-md-3 mb-0">
                {{ form.valor_parcela|as_crispy_field }}
            </div>
            <div class="form-group col-md-3 mb-0">
                {{ form.valor_pago|as_crispy_field }}
            </div>
        </div>
        <div class="form-row">
            <div class="form-group col-md-3 mb-0">
                {{ form.status|as_crispy_field }}
            </div>
            <div class="form-group col-md-3 mb-0">
                {{ form.conta_caixa|as_crispy_field }}
            </div>
            <div class="form-group col-md-3 mb-0">
                {{ form.banco|as_crispy_field }}
            </div>
            <div class="form-group col-md-3 mb-0">
                {{ form.origem|as_crispy_field }}
            </div>
        </div>       
        <div class="form-row">
            <div class="form-group col-md-12 mb-0">
                {{ form.entrada|as_crispy_field }}
            </div>
        </div>
        <div class="form-row">
            <div class="form-group col-md-12 mb-0">
                {{ form.obs|as_crispy_field }}
            </div>
        </div>
    </form>
</div>
{% endblock %}

{% block extrascripts %}
{{ form.media }}
<script>
     
    const dt_emi = document.getElementById('id_data_emissao');
    dt_emi.addEventListener("change", dt_emi_function);

    const dt_venc = document.getElementById('id_data_vencimento');
    dt_venc.addEventListener("change", dt_venc_function);

    const dt_pgto = document.getElementById('id_data_pagamento');
    dt_pgto.addEventListener("change", dt_pagamento_function);


    function quitar(e) {
        let dt = document.getElementById("id_data_vencimento").value
        let val_parc = document.getElementById("id_valor_parcela").value
        document.getElementById("id_data_pagamento").value = dt
        document.getElementById("id_valor_pago").value = val_parc
        document.getElementById("id_status").value = 2
        document.getElementById("salvar").click()
        };


    function dt_emi_function(e) {
        const today = new Date();
        let dt = document.getElementById("id_data_emissao").value;
        let new_date = addDays(today, dt);
        document.getElementById("id_data_emissao").value = new_date
        };


    function dt_venc_function(e) {
        let dt = retDate(document.getElementById("id_data_emissao").value);
        let vc = document.getElementById("id_data_vencimento").value;
        let new_date = addDays(dt, vc);
        document.getElementById("id_data_vencimento").value = new_date
        };

    function dt_pagamento_function(e) {
        let vc = retDate(document.getElementById("id_data_vencimento").value);
        let pg = document.getElementById("id_data_pagamento").value;
        let new_date = addDays(vc, pg);
        document.getElementById("id_data_pagamento").value = new_date
        };


    function addDays(date, days) {
        const isNum = checkValue(days);
        console.log(isNum);
        if (isNum){
            const nDays = parseInt(days, 10);
            var newDate = new Date(date);
            newDate.setDate(newDate.getDate() + nDays);
            const dataFormatada = ((newDate.getDate() ) + "/" + ((newDate.getMonth() + 1)) + "/" + newDate.getFullYear());                 
            return dataFormatada;        
        } else {
            return days
        }
        };

    function checkValue(val){
        const num = parseInt(val, 10);
        console.log(num);
        return !isNaN(val)
        };
    
    function retDate(dateString){
        var parts =dateString.split('/');
        // Please pay attention to the month (parts[1]); JavaScript counts months from 0:
        // January - 0, February - 1, etc.
        var mydate = new Date(parts[2], parts[1] - 1, parts[0]); 
        console.log(mydate.toDateString());
        return mydate
    }

</script>

{% endblock extrascripts %}

financeiro/templates/financeiro/cp_list.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}

<div class="container-fluid">

  <div class="form-row">
    <div class="form-group col-md-4 mb-0">
      <h4><strong>Contas a Pagar</strong></h4>
    </div>
    <div class="form-group col-md-4 mb-0">
      <form method="get" id="acao_lote"></form>
      {{ lote.opcoes|as_crispy_field }}
    </div>
    <div class="form-group col-md-4 mb-0">
      <button type="button" class="btn btn-primary" onclick="lote(this);">Executar</button>
      <button id="filter" class="filter-pedido btn btn-primary" type="button" name="button" data-form-url="{% url 'financeiro:cp_filter' %}">
        <span class="fa fa-filter mr-2"></span>Filtrar
      </button>
    </div>
  </form>
</div>

  <p> </p>   
  {% include "financeiro/cp_list_table.html" %}     


</div>

<div class="modal fade" id="filtro" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered modal-lg " role="document">
    <div class="modal-content">
      
      <div class="modal-header">
        <h5 class="modal-title" id="send_mail">Filtro do Contas a Pagar</h5>       
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
      </div>

      <div class="modal-body">
        <div class="container" id="filtro">
          <form method="get" id="filtro-form">
            {{ lista.form|crispy }}
            <button type="submit" class="btn btn-primary" >Filtrar</button>
          </form>
        </div>
      </div>

    </div>
  </div>
</div>

{% endblock content %}

{% block extrascripts %}
<script type="text/javascript">

  $(".detail").click(function(){
    var url = $(this).attr('data-form-url');
    location.href = url  
  });

  $(".read").click(function(){
    var url = $(this).attr('data-form-url');
    $(this).modalForm({formURL: $(this).data("form-url")}); 
  });

  $("#filter").click(function () {
    $("#filtro").modal('toggle')
  });


  function toggle(source) {
    var checkboxes = document.querySelectorAll('input[type="checkbox"]');
    for (var i = 0; i < checkboxes.length; i++) {
        if (checkboxes[i] != source)
            checkboxes[i].checked = source.checked;
    }
  }

  function lote(source) {
    let checkboxes = document.querySelectorAll('input[name="chk"]:checked');
    let lote_opt = document.getElementById("id_opcoes").value
    let values = [];
    checkboxes.forEach((checkbox) => {
        values.push(checkbox.value);
    });
    console.log(values);
    console.log(lote_opt);
    send_lote(values, lote_opt)
  } 

  function send_lote(chkeds, opt) {

    let data = new FormData();
    data.append('chkeds', chkeds);;
    data.append('opt', opt);
    // add form input from hidden input elsewhere on the page
    data.append('csrfmiddlewaretoken', '{{ csrf_token }}')

    console.log(JSON.stringify(data))

    fetch("{% url 'financeiro:cp_lote' %}", {
        method: 'POST',
        body: data,
        credentials: 'same-origin',
        headers: {"X-CSRFToken": '{{ csrf_token }}'}
    }).then((response) => {
        console.log(response)
    }).then((res) => {
        if (res.status === 201) {
            console.log("Post successfully created!")
        }
    }).catch((error) => {
        console.log(error)
    })
  }

</script>
{% endblock extrascripts %}

financeiro/templates/financeiro/cr_list.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}

<div class="container-fluid">

  <div class="form-row">
    <div class="form-group col-md-4 mb-0">
      <h4><strong>Contas a Receber</strong></h4>
    </div>
    <div class="form-group col-md-4 mb-0">
      <form method="get" id="acao_lote"></form>
      {{ lote.opcoes|as_crispy_field }}
    </div>
    <div class="form-group col-md-4 mb-0">
      <button type="button" class="btn btn-primary" onclick="lote(this);">Executar</button>
      <button id="filter" class="filter-pedido btn btn-primary" type="button" name="button" data-form-url="{% url 'financeiro:cp_filter' %}">
        <span class="fa fa-filter mr-2"></span>Filtrar
      </button>
      <a href="/fin/cr/new"> <button type="button" class="btn btn-primary">Novo</button></a>
    </div>
  </form>
</div>

  <p> </p>   
  {% include "financeiro/cr_list_table.html" %}     


</div>

<div class="modal fade" id="filtro" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered modal-lg " role="document">
    <div class="modal-content">
      
      <div class="modal-header">
        <h5 class="modal-title" id="send_mail">Filtro do Contas a Pagar</h5>       
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
      </div>

      <div class="modal-body">
        <div class="container" id="filtro">
          <form method="get" id="filtro-form">
            {{ lista.form|crispy }}
            <button type="submit" class="btn btn-primary" >Filtrar</button>
          </form>
        </div>
      </div>

    </div>
  </div>
</div>

{% endblock content %}

{% block extrascripts %}
<script type="text/javascript">

  $(".detail").click(function(){
    var url = $(this).attr('data-form-url');
    location.href = url  
  });

  $(".read").click(function(){
    var url = $(this).attr('data-form-url');
    $(this).modalForm({formURL: $(this).data("form-url")}); 
  });

  $("#filter").click(function () {
    $("#filtro").modal('toggle')
  });


  function toggle(source) {
    var checkboxes = document.querySelectorAll('input[type="checkbox"]');
    for (var i = 0; i < checkboxes.length; i++) {
        if (checkboxes[i] != source)
            checkboxes[i].checked = source.checked;
    }
  }

  function lote(source) {
    let checkboxes = document.querySelectorAll('input[name="chk"]:checked');
    let lote_opt = document.getElementById("id_opcoes").value
    let values = [];
    checkboxes.forEach((checkbox) => {
        values.push(checkbox.value);
    });
    console.log(values);
    console.log(lote_opt);
    send_lote(values, lote_opt)
  } 

  function send_lote(chkeds, opt) {

    let data = new FormData();
    data.append('chkeds', chkeds);;
    data.append('opt', opt);
    // add form input from hidden input elsewhere on the page
    data.append('csrfmiddlewaretoken', '{{ csrf_token }}')

    console.log(JSON.stringify(data))

    fetch("{% url 'financeiro:cp_lote' %}", {
        method: 'POST',
        body: data,
        credentials: 'same-origin',
        headers: {"X-CSRFToken": '{{ csrf_token }}'}
    }).then((response) => {
        console.log(response)
    }).then((res) => {
        if (res.status === 201) {
            console.log("Post successfully created!")
        }
    }).catch((error) => {
        console.log(error)
    })
  }

</script>
{% endblock extrascripts %}